name: Publish to PyPi

on:
  release:
    types: [published] # Run when a new published release is detected.

env:
  BUILD_ARTIFACT_NAME: "poetry-build-dist"
  REPOSITORY_PUSH_URL: "https://test.pypi.org/legacy/"
  REPOSITORY_URL: "https://test.pypi.org/p/testdeployofpypi"

permissions:
  contents: read

jobs:
  release-build-poetry:
    uses: nicburgt/.github/.github/workflows/poetry-build.yml@fd17d345f3dbc2bf188a4fbaf7d633491438f3ef
    with:
      version: ${{ github.event.release.tag_name }}
      poetry-build-artifact-name: $BUILD_ARTIFACT_NAME

  # unfortunately, this step cannot be made into a reusable workflow (yet).
  # see https://github.com/pypi/warehouse/issues/11096.
  # We could use a global user + password combination to publish to pypi,
  # but this is a lot less secure than a per repository OIDC token which expires
  # And only grants access to a single repository, instead of all the repositories
  # published under a user.
  pypi-publish:
    runs-on: ubuntu-latest
    needs: [release-build-poetry]
    permissions:
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: testpypi
      url: ${{env.REPOSITORY_URL}}/${{ github.event.release.tag_name }}
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: $BUILD_ARTIFACT_NAME
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: ${{ env.REPOSITORY_PUSH_URL }}
