name: Python Default CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeqa:
    uses: nicburgt/.github/.github/workflows/codeqa.yml@18d3b42583642bf014aaf29f9c98b663a0611a53
    with:
      python-version: ${{ inputs.python-version }}
  tests:
    uses: nicburgt/.github/.github/workflows/tests.yml@18d3b42583642bf014aaf29f9c98b663a0611a53
    with:
      python-version: ${{ inputs.python-version }}
      test-results-artifact-name: 'coverage-results'
