name: Python Default CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeqa:
    uses: nicburgt/.github/.github/workflows/codeqa.yml@fd17d345f3dbc2bf188a4fbaf7d633491438f3ef
    with:
      python-version: ${{ inputs.python-version }}
  tests:
    uses: nicburgt/.github/.github/workflows/tests.yml@fd17d345f3dbc2bf188a4fbaf7d633491438f3ef
    with:
      python-version: ${{ inputs.python-version }}
      test-results-artifact-name: 'coverage-results'
