name: Python Default CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeqa:
    uses: nicburgt/.github/.github/workflows/codeqa.yml@cea79ef34e69a346abe36f79f14c45fc706d8d18
    with:
      python-version: ${{ inputs.python-version }}
  tests:
    uses: nicburgt/.github/.github/workflows/tests.yml@442d683b7e6280aa4cbf900f2a258b1ae2ea13d0
    with:
      python-version: ${{ inputs.python-version }}
      test-results-artifact-name: 'coverage-results'
