name: Python Default CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeqa:
    uses: nicburgt/.github/workflows/codeqa.yml@b69f174f740af324f6539ff1f212d82ca31813f4
    with:
      python-version: ${{ inputs.python-version }}
  tests:
    uses: nicburgt/.github/workflows/tests.yml@b69f174f740af324f6539ff1f212d82ca31813f4
    with:
      python-version: ${{ inputs.python-version }}
      test-results-artifact-name: 'coverage-results'
